
name: push

on:
  push:
    branches:
      - test
jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - name: Run script
          run: |
            echo ${{ vars.TEST_ENV }}
            echo ${{ github.ref_name }}
            echo test, and deploy your project.
