name: schedule

on:
    schedule:
      - cron: '50 15 * * *'
    workflow_dispatch:
jobs:
    dummy:
    #   if: ${{ false }}
      runs-on: ubuntu-latest
      steps:
        - name: Run script
          run: |
            echo ${{ vars.TEST_ENV }}
            echo ${{ github.ref_name }}
            echo test, and deploy your project.
