on:
    schedule:
      # Run at 23:00 UTC every day
      - cron: '0 14 * * *'
    # Manual triggering with input parameters
    workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Runs a set of commands using the runners shell
        - name: Run Trigger
          run: |
            echo ${{ vars.TEST_ENV }}
            echo test, and deploy your project.
  