on:
    schedule:
      - cron: '50 15 * * *'
    workflow_dispatch:
jobs:
    dummy:
    #   if: ${{ false }}
      runs-on: ubuntu-latest
      steps:
        - run: |
          echo ${{ vars.TEST_ENV }}
          echo test, and deploy your project.
